"""empty message

Revision ID: 3108bc894b6b
Revises: c58a84b3b4a1
Create Date: 2022-05-13 11:28:06.710613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3108bc894b6b'
down_revision = 'c58a84b3b4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_product', 'img',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('image_product', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('image_product', 'mimetype',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('prouduct_size', 'name',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('prouduct_size', 'qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prouduct_size', 'qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prouduct_size', 'name',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('image_product', 'mimetype',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('image_product', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('image_product', 'img',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
