"""empty message

Revision ID: 33fb3fb493d0
Revises: bdf803c46498
Create Date: 2022-05-13 21:37:59.618145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33fb3fb493d0'
down_revision = 'bdf803c46498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_product', sa.Column('img', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'image_product', ['img'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_product', type_='unique')
    op.drop_column('image_product', 'img')
    # ### end Alembic commands ###
