"""empty message

Revision ID: 6caae20ed509
Revises: 33fb3fb493d0
Create Date: 2022-05-14 13:23:10.682192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6caae20ed509'
down_revision = '33fb3fb493d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['slug'])
    op.add_column('product', sa.Column('category_slug', sa.String(length=256), nullable=True))
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_slug'], ['slug'])
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_category_id_fkey', 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category_slug')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
