"""empty message

Revision ID: 6ea30edc2fb5
Revises: 2f26755360fc
Create Date: 2022-05-14 13:48:51.038074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea30edc2fb5'
down_revision = '2f26755360fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('name_img', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('slug', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('second_name', sa.String(length=120), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('email_mailing', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('amount_of_purchases', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('slug', sa.String(length=55), nullable=True),
    sa.Column('category_slug', sa.String(length=55), nullable=True),
    sa.ForeignKeyConstraint(['category_slug'], ['category.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('subcategory_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('slug', sa.String(length=55), nullable=True),
    sa.Column('subcategory_slug', sa.String(length=55), nullable=True),
    sa.ForeignKeyConstraint(['subcategory_slug'], ['subcategory.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_slug', sa.String(length=256), nullable=True),
    sa.Column('subcategory_slug', sa.String(length=256), nullable=True),
    sa.Column('subcategory_type_slug', sa.String(length=256), nullable=True),
    sa.Column('brand_slug', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(decimal_return_scale=2), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('article', sa.String(length=256), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('name_img', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('price_discount', sa.Float(decimal_return_scale=2), nullable=True),
    sa.ForeignKeyConstraint(['brand_slug'], ['brand.slug'], ),
    sa.ForeignKeyConstraint(['category_slug'], ['category.slug'], ),
    sa.ForeignKeyConstraint(['subcategory_slug'], ['subcategory.slug'], ),
    sa.ForeignKeyConstraint(['subcategory_type_slug'], ['subcategory_type.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img')
    )
    op.create_table('image_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img')
    )
    op.create_table('prouduct_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prouduct_size')
    op.drop_table('image_product')
    op.drop_table('product')
    op.drop_table('subcategory_type')
    op.drop_table('subcategory')
    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('brand')
    # ### end Alembic commands ###
