"""empty message

Revision ID: bdf803c46498
Revises: bcc1e296de11
Create Date: 2022-05-13 21:37:30.295443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdf803c46498'
down_revision = 'bcc1e296de11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_product_img_key', 'image_product', type_='unique')
    op.drop_column('image_product', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_product', sa.Column('img', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.create_unique_constraint('image_product_img_key', 'image_product', ['img'])
    # ### end Alembic commands ###
